// Generated by https://quicktype.io

export interface ResponseLists {
    id:                number;
    name:              string;
    color:             string;
    products_by_lists: ProductsByList[];
}

export interface ProductsByList {
    name:    string;
    quality: string;
    base?:    number;
    xp3?:    number;
    xp4?:    number;
    xp5?:    number;
    xp6?:    number;
}

export interface List {
    id:                number;
    name:              string;
    color:             string;
    products_by_lists: ProductsByNewList[];
}

export interface ProductsByNewList {
    name:    string;
    quality: string;
    prices:  Price[];
}

export interface Price {
    list:  string;
    price: number;
}
