// Generated by https://quicktype.io

export interface ResponseLists {
    id:                number;
    name:              string;
    color:             string;
    products_by_lists: ProductsByList[];
}

export interface ProductsByList {
    name:    string;
    quality: string;
    xp31?:    number;
    xp41?:    number;
    xp51?:    number;
    xp61?:    number;
    xp71?:    number;
}

// Generated by https://quicktype.io

export interface List {
    id:                number;
    name:              string;
    color:             string;
    products_by_lists: ProductsByNewList[];
}

export interface ProductsByNewList {
    name:    string;
    quality: string;
    prices:  Price[];
}

export interface Price {
    list:  string;
    price: number;
}
