// Generated by https://quicktype.io

export interface ResponseLogin {
    user:  User;
    token: string;
}

export interface User {
    id:       number;
    name:     string;
    email:    string;
    password: string;
    role:     string;
}

// Generated by https://quicktype.io

export interface ResponseProducts {
    phones: Phone[];
}

export interface Phone {
    id:            number;
    name:          string;
    list_price:    number;
    qty_available: number;
}

