// Generated by https://quicktype.io

export interface ResponseLogin {
    user:  User;
    token: string;
}

export interface User {
    id:       number;
    name:     string;
    email:    string;
    password: string;
    role:     string;
}
