// Generated by https://quicktype.io

export interface ResponseLogin {
    user:  User;
    token: string;
}

export interface User {
    id:       number;
    name:     string;
    email:    string;
    password: string;
    role:     string;
}

// Generated by https://quicktype.io

export interface ResponseProduct {
    id:         number;
    name:       string;
    list_price: number;
    type:       Type;
    color:      Color;
    image_512: string;
}

export enum Color {
    AAA = "aaa",
    Black = "BLACK",
    Blue = "BLUE",
    ColorBlack = "Black",
    ColorINCELL = "IN-CELL",
    Empty = "/",
    G530 = "G530",
    Golden = "GOLDEN",
    Grey = "GREY",
    InCell = "in-cell",
    K580 = "K580",
    OLED = "oled",
    Or = "or",
    Silver = "SILVER",
    Super = "super",
    WF = "W/F",
    White = "WHITE",
}

export enum Type {
    AAA = "aaa",
    AMOLED = "amoled",
    Black = "BLACK",
    Cof = "cof",
    Cog = "cog",
    Golden = "GOLDEN",
    InCell = "in-cell",
    Incell = "INCELL",
    OLED = "oled",
    OnCell = "on-cell",
    Or = "or",
    Original = "original",
    Promocion = "(promocion)",
    Promociones = "(promociones)",
    Promoción = "(PROMOCIÓN)",
    TypeINCELL = "IN-CELL",
    TypeIncell = "incell",
    TypeOLED = "OLED",
    TypeOR = "OR",
    TypeOr = "Or",
    TypePROMOCION = "(PROMOCION)",
    TypePromocion = "(Promocion)",
    White = "WHITE",
}

// Generated by https://quicktype.io

export interface ResponseProductId {
    id:         number;
    name:       string;
    description:string;
    image:      string;
    list_price: number;
    type:       string;
    color:      string;
    quantity:   number;
}


