// Generated by https://quicktype.io

export interface SaleOfProduct {
    id:              number;
    name:            string;
    product_uom_qty: number;
    create_date:     string;
    warehouse_id:    Array<WarehouseIDEnum | number>;
    product_id:      Array<number | string>;
}

export enum WarehouseIDEnum {
    Bodega = "BODEGA",
}

