// Generated by https://quicktype.io

export interface ResponseStock {
    id:          number;
    initial100P: number;
    final100P:   number;
    initial320P: number;
    final320P:   number;
    initialWh:   number;
    finalWh:     number;
    initialGar:  number;
    finalGar:    number;
    createdAt:   string;
    updatedAt:   string;
}
