// Generated by https://quicktype.io

export interface LoginOdoo {
    jsonrpc: string;
    method:  string;
    params:  Params;
}

export interface Params {
    service: string;
    method:  string;
    args:    string[];
}

// Generated by https://quicktype.io
// Generated by https://quicktype.io

export interface ResSearchRead {
    jsonrpc: string;
    id:      null;
    result:  Result[];
}

export interface Result {
    id:                            number;
    product_id:                    Array<number | string>;
    product_tmpl_id:               Array<number | string>;
    product_uom_id:                Array<ProductUomIDEnum | number>;
    priority:                      boolean | string;
    company_id:                    Array<CompanyIDEnum | number> | boolean;
    location_id:                   Array<LocationIDEnum | number>;
    storage_category_id:           boolean;
    cyclic_inventory_frequency:    number;
    lot_id:                        boolean;
    sn_duplicated:                 boolean;
    package_id:                    boolean;
    owner_id:                      boolean;
    quantity:                      number;
    reserved_quantity:             number;
    available_quantity:            number;
    in_date:                       string;
    tracking:                      Tracking;
    on_hand:                       boolean;
    product_categ_id:              Array<ProductCategIDEnum | number>;
    inventory_quantity:            number;
    inventory_quantity_auto_apply: number;
    inventory_diff_quantity:       number;
    inventory_date:                boolean | string;
    last_count_date:               boolean | string;
    inventory_quantity_set:        boolean;
    is_outdated:                   boolean;
    user_id:                       boolean;
    __last_update:                 string;
    display_name:                  string;
    create_uid:                    Array<CreateUidEnum | number>;
    create_date:                   string;
    write_uid:                     Array<WriteUidEnum | number>;
    write_date:                    string;
    value:                         number;
    currency_id:                   Array<CurrencyIDEnum | number> | boolean;
    accounting_date:               boolean;
}

export enum CompanyIDEnum {
    XPLCDFactory = "XP lcd factory",
}

export enum CreateUidEnum {
    Exterior = "Exterior",
    Pc87320321 = "PC87 320-321",
    YenyWen = "Yeny Wen",
}

export enum CurrencyIDEnum {
    Mxn = "MXN",
}

export enum LocationIDEnum {
    GARStock = "GAR/Stock",
    PartnerLocationsCustomers = "Partner Locations/Customers",
    PartnerLocationsVendors = "Partner Locations/Vendors",
    PhysicalLocationsInterWarehouseTransit = "Physical Locations/Inter-warehouse transit",
    The100PStock = "100 P/Stock",
    The320Stock = "320/Stock",
    The320StockStock = "320/Stock/Stock",
}

export enum ProductCategIDEnum {
    All = "All",
    PoS = "PoS",
}

export enum ProductUomIDEnum {
    Units = "Units",
}

export enum Tracking {
    None = "none",
}

export enum WriteUidEnum {
    OdooBot = "OdooBot",
    Pc87100P = "PC87 100-P",
    Pc87320321 = "PC87 320-321",
    YenyWen = "Yeny Wen",
}

export interface ResLoginOdoo {
    jsonrpc: string;
    id:      null;
    result:  number;
}
