// Generated by https://quicktype.io

export interface ResponseAllUsers {
    id:              number;
    name:            string;
    email:           string;
    role:            string;
    access_to_lists: boolean;
}
