// Generated by https://quicktype.io

export interface ResponseUsers {
    previousPage: boolean;
    nextPage:     boolean;
    data:         DataUser[];
}

export interface DataUser {
    id:              number;
    name:            string;
    email:           string;
    role:            string;
    access_to_lists: boolean;
}
